editied footer - removed node branding (powered by)
CMU-17313Q/fall23-nodebb-nirvana pull request #31
Opened 2023-09-16 09:16 UTC by abdullaalsulaiti

removed the footer and nodebb powered by

2023-09-17 06:18 UTC, Inverseit requested changes

2023-09-17 06:18 UTC, Inverseit commented on install/data/footer.json
> +			"html": "<footer id='footer' class='container footer'></footer>",
Can you write some text here? Something like "NodeBB extended by Nirvana"? It is up to you, tho

2023-09-18 10:51 UTC, dananaimi commented
<img width="1427" alt="sc" src="https://github.com/CMU-17313Q/fall23-nodebb-nirvana/assets/103209903/7931b93c-dd81-4ba8-bec4-dd4ee718d6f4">

2023-09-18 10:52 UTC, abdullaalsulaiti commented
<img width="1427" alt="sc" src="https://github.com/CMU-17313Q/fall23-nodebb-nirvana/assets/105718555/66a83d15-b570-48b2-8944-c9fc54dbc96b">

2023-09-18 10:58 UTC, Inverseit approved these changes
Works

2023-09-18 11:02 UTC, merged